export const {
  VITE_API_BASE_PATH: API_BASE_PATH,
  VITE_API_PREFIX: API_PREFIX,
  VITE_SOCKET_PATH_NOTIFY: SOCKET_PATH_NOTIFY,
  VITE_SOCKET_PATH_EXTRACT: SOCKET_PATH_EXTRACT,
} = import.meta.env;
